# Generated by Django 6.0.5 on 2026-09-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annuaire', '0014_account_last_feed_seen_at_person_created_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('start', models.DateTimeField(verbose_name='Début')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='Journée entière')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('reminder_sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Rappel envoyé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='annuaire.person', verbose_name='Créé par')),
                ('organisers', models.ManyToManyField(blank=True, related_name='organised_events', to='annuaire.person', verbose_name='Organisateurs·rices')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Événement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Accès groupe à événement',
                'verbose_name_plural': 'Accès groupes à événements',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventGroupAccess', to='auth.group', verbose_name='Groupes autorisés'),
        ),
        migrations.AddConstraint(
            model_name='eventgroupaccess',
            constraint=models.UniqueConstraint(fields=('event', 'group'), name='unique_event_group_access'),
        ),
    ]
