# Generated by Django 6.0.5 on 2026-09-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0014_account_last_feed_seen_at_person_created_at'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('maybe', 'Peut-être')], max_length=10, verbose_name='Réponse')),
                ('guest_count', models.PositiveSmallIntegerField(default=0, verbose_name='Accompagnants')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event', verbose_name='Événement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='annuaire.person', verbose_name='Personne')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'constraints': [models.UniqueConstraint(fields=('event', 'person'), name='unique_event_person_rsvp')],
            },
        ),
    ]
