# Generated by Django 6.0.5 on 2026-05-16 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Membre du personnel'),
        ),
        migrations.AlterField(
            model_name='account',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Doit changer le mot de passe'),
        ),
        migrations.AlterField(
            model_name='chalet',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='chalet',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordonnées GPS'),
        ),
        migrations.AlterField(
            model_name='chalet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chalet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='presencepsv',
            name='chalet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.chalet', verbose_name='Chalet'),
        ),
        migrations.AlterField(
            model_name='presencepsv',
            name='end_date',
            field=models.DateField(verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='presencepsv',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.person', verbose_name='Personne'),
        ),
        migrations.AlterField(
            model_name='presencepsv',
            name='start_date',
            field=models.DateField(verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascending_relations', to='annuaire.person', verbose_name='Personne'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descending_relations', to='annuaire.person', verbose_name='En relation avec'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relationship_type',
            field=models.IntegerField(choices=[(0, 'mariage'), (1, 'conjoint'), (2, 'parent'), (3, 'enfant')], verbose_name='Type de relation'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
