# Generated by Django 6.0.5 on 2026-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0002_alter_account_email_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalet',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_chalets', to='annuaire.person', verbose_name='Propriétaires'),
        ),
    ]
