# Generated by Django 6.0.5 on 2026-08-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0003_chalet_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_birthday', models.BooleanField(blank=True, default=False, verbose_name='Recevoir un rappel pour les anniversaires')),
                ('notify_on_new_blog_post', models.BooleanField(blank=True, default=False, verbose_name='Recevoir une notification pour les nouveaux articles')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='annuaire.person', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Paramètres de notification',
                'verbose_name_plural': 'Paramètres de notification',
            },
        ),
    ]
