# Generated by Django 6.0.5 on 2026-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0005_person_latitude_person_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True, verbose_name='Genre'),
        ),
    ]
