# Generated by Django 6.0.5 on 2026-08-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0006_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
