# Generated by Django 6.0.5 on 2026-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0007_remove_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='chalet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
