# Generated by Django 6.0.5 on 2026-08-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0008_chalet_latitude_chalet_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='managed_profiles', to='annuaire.person', verbose_name='Propriétaires'),
        ),
    ]
