# Generated by Django 6.0.5 on 2026-08-22 12:19

import re

from django.db import migrations

COORDINATE_PATTERN = re.compile(r"(-?\d+\.?\d*)\s*[nN]?\s*[,;/]\s*(-?\d+\.?\d*)\s*[eE]?")


def salvage_gps_coordinates(apps, schema_editor):
    Chalet = apps.get_model("annuaire", "Chalet")
    for chalet in Chalet.objects.filter(latitude__isnull=True, longitude__isnull=True).exclude(
        gps_coordinates__isnull=True
    ).exclude(gps_coordinates=""):
        match = COORDINATE_PATTERN.search(chalet.gps_coordinates)
        if not match:
            print(f"Could not parse gps_coordinates for chalet {chalet.pk!r} ({chalet.name!r}): {chalet.gps_coordinates!r}")
            continue
        chalet.latitude, chalet.longitude = match.group(1), match.group(2)
        chalet.save(update_fields=["latitude", "longitude"])


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0009_person_owners'),
    ]

    operations = [
        migrations.RunPython(salvage_gps_coordinates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='chalet',
            name='gps_coordinates',
        ),
    ]
