# Generated by Django 6.0.5 on 2026-08-22 17:47

from django.db import migrations, models


def backfill_notifications_checked(apps, schema_editor):
    """Existing Settings rows (and any Person predating the Settings model, whose
    post_save signal never ran) are backfilled to the new all-checked default. No
    account filter -- accountless "fiches" with an email on file are backfilled
    too and will receive notification mail like anyone else (deliberate choice,
    see ROADMAP #77)."""
    Person = apps.get_model("annuaire", "Person")
    Settings = apps.get_model("annuaire", "Settings")
    Settings.objects.bulk_create(
        [Settings(person=person) for person in Person.objects.filter(settings__isnull=True)]
    )
    Settings.objects.update(notify_on_birthday=True, notify_on_new_blog_post=True)


class Migration(migrations.Migration):
    dependencies = [
        ("annuaire", "0010_remove_chalet_gps_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="notify_on_birthday",
            field=models.BooleanField(blank=True, default=True, verbose_name="Recevoir un rappel pour les anniversaires"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="notify_on_new_blog_post",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Recevoir une notification pour les nouveaux articles"
            ),
        ),
        migrations.RunPython(backfill_notifications_checked, migrations.RunPython.noop),
    ]
