# Generated by Django 6.0.5 on 2026-09-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0011_notifications_opt_in_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de décès'),
        ),
        migrations.AddField(
            model_name='person',
            name='deceased',
            field=models.BooleanField(default=False, verbose_name='Décédé·e'),
        ),
    ]
