# Generated by Django 6.0.5 on 2026-09-07 16:38

import django.contrib.postgres.search
from django.db import migrations, models

from annuaire.search.migration_ops import create_gin_index_operation


def backfill_person_search_index(apps, schema_editor):
    from annuaire.search.indexing import apply_index, build_index_payload
    from annuaire.search.registry import get_spec
    from annuaire.models import Person

    spec = get_spec(Person)
    for person in Person.objects.iterator():
        apply_index(Person, person.pk, build_index_payload(person, spec))


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0012_person_death_date_person_deceased'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche'),
        ),
        migrations.AddField(
            model_name='person',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche'),
        ),
        create_gin_index_operation("annuaire_person_search_vector_gin", "annuaire_person"),
        migrations.RunPython(backfill_person_search_index, migrations.RunPython.noop),
    ]
