# Generated by Django 6.0.5 on 2026-09-07 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0013_person_search_text_person_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_feed_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière consultation du fil'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Date de création'),
            preserve_default=False,
        ),
    ]
