# Generated by Django 6.0.5 on 2026-09-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0014_account_last_feed_seen_at_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notify_on_event',
            field=models.BooleanField(blank=True, default=True, verbose_name="Recevoir les annonces et rappels d'événements"),
        ),
    ]
