# Generated by Django 6.0.5 on 2026-09-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0015_settings_notify_on_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='calendar_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Jeton calendrier'),
        ),
    ]
