# Generated by Django 6.0.5 on 2026-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annuaire", "0016_account_calendar_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_place",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Lieu de naissance"),
        ),
        migrations.AddField(
            model_name="person",
            name="death_place",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Lieu de décès"),
        ),
        migrations.AddField(
            model_name="relation",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AddField(
            model_name="relation",
            name="marriage_place",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Lieu du mariage"),
        ),
    ]
