# Generated by Django 6.0.5 on 2026-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0017_person_birth_place_person_death_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='export_privacy',
            field=models.CharField(blank=True, choices=[('auto', 'Automatique (masqué·e tant que vivant·e)'), ('share', 'Toujours partager'), ('redact', 'Toujours masquer')], default='auto', max_length=6, verbose_name='Confidentialité dans les exports'),
        ),
    ]
