# Generated by Django 6.0.5 on 2026-09-12 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0018_person_export_privacy'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64, verbose_name="Identifiant de l'objet")),
                ('object_repr', models.CharField(max_length=200, verbose_name='Objet')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('restore', 'Restauration'), ('purge', 'Purge définitive'), ('membership_add', 'Ajout à un groupe'), ('membership_remove', "Retrait d'un groupe")], max_length=20, verbose_name='Action')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Modifications')),
                ('actor_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Auteur (archivé)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'objet")),
            ],
            options={
                'verbose_name': "Événement d'audit",
                'verbose_name_plural': "Événements d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
