# Generated by Django 6.0.5 on 2026-09-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0019_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='privacy_notice_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation de la politique de confidentialité"),
        ),
        migrations.AddField(
            model_name='account',
            name='privacy_notice_version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Version acceptée de la politique de confidentialité'),
        ),
    ]
