# Generated by Django 6.0.5 on 2026-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0020_account_privacy_notice_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anonymisé·e le'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('restore', 'Restauration'), ('purge', 'Purge définitive'), ('membership_add', 'Ajout à un groupe'), ('membership_remove', "Retrait d'un groupe"), ('anonymise', 'Anonymisation')], max_length=20, verbose_name='Action'),
        ),
    ]
