# Generated by Django 6.0.5 on 2026-09-12 18:46

from django.db import migrations, models

import annuaire.models


class Migration(migrations.Migration):
    dependencies = [
        ("annuaire", "0021_person_anonymised_at_alter_auditevent_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Nom du site")),
                ("wordmark", models.CharField(blank=True, default="", max_length=100, verbose_name="Wordmark")),
                ("tagline", models.CharField(blank=True, default="", max_length=255, verbose_name="Accroche")),
                (
                    "sender_address",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Adresse d'expédition des emails"
                    ),
                ),
                (
                    "feedback_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Laisser vide pour masquer le lien « Signaler un bug » du menu.",
                        verbose_name="Lien de retour/signalement",
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Paris", max_length=64, verbose_name="Fuseau horaire")),
                (
                    "default_language",
                    models.CharField(
                        blank=True,
                        choices=annuaire.models._language_choices,
                        default="",
                        help_text="Sans effet tant que l'internationalisation (phase 15.4) n'est pas en place.",
                        max_length=10,
                        verbose_name="Langue par défaut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configuration du site",
            },
        ),
    ]
