# Generated by Django 6.0.5 on 2026-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annuaire", "0023_siteconfig_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="brand_accent_dark",
            field=models.CharField(blank=True, default="", max_length=7, verbose_name="Couleur d'accent (sombre)"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="brand_accent_light",
            field=models.CharField(blank=True, default="", max_length=7, verbose_name="Couleur d'accent (clair)"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="brand_primary_dark",
            field=models.CharField(blank=True, default="", max_length=7, verbose_name="Couleur principale (sombre)"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="brand_primary_light",
            field=models.CharField(blank=True, default="", max_length=7, verbose_name="Couleur principale (clair)"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="branding/", verbose_name="Favicon"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/", verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="theme",
            field=models.CharField(
                choices=[("alpenglow", "Alpenglow")], default="alpenglow", max_length=20, verbose_name="Thème"
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Dernière modification"),
        ),
    ]
