# Generated by Django 6.0.5 on 2026-09-13 07:46

import annuaire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0024_siteconfig_brand_accent_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.CharField(blank=True, choices=annuaire.models._language_choices, default='', max_length=10, verbose_name='Langue'),
        ),
    ]
