# Generated by Django 6.0.5 on 2026-09-07 10:39

import django.db.models.deletion
import photos.storage
import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annuaire', '0012_person_death_date_person_deceased'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_albums', to='annuaire.person', verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.album', verbose_name='Album')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Accès groupe à album',
                'verbose_name_plural': 'Accès groupes à albums',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='photo_albums', through='photos.AlbumGroupAccess', to='auth.group', verbose_name='Groupes autorisés'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=photos.storage.get_photo_storage, upload_to='originals/', validators=[photos.validators.validate_photo_extension, photos.validators.validate_photo_size], verbose_name='Fichier')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Légende')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Pris le')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur')),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=photos.storage.get_photo_storage, upload_to='thumbnails/', verbose_name='Vignette')),
                ('web', models.ImageField(blank=True, null=True, storage=photos.storage.get_photo_storage, upload_to='web/', verbose_name='Rendu web')),
                ('derivative_status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Terminé'), ('error', 'Erreur')], db_index=True, default='pending', max_length=20, verbose_name='Statut des dérivés')),
                ('derivative_error', models.CharField(blank=True, default='', max_length=255, verbose_name='Erreur de dérivés')),
                ('derivatives_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Dérivés générés le')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.album', verbose_name='Album')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to='annuaire.person', verbose_name='Déposé par')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['uploaded_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo', verbose_name='Photo de couverture'),
        ),
        migrations.AddConstraint(
            model_name='albumgroupaccess',
            constraint=models.UniqueConstraint(fields=('album', 'group'), name='unique_album_group_access'),
        ),
    ]
