# Generated by Django 6.0.5 on 2026-09-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0012_person_death_date_person_deceased'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_x', models.FloatField(blank=True, null=True, verbose_name='Position X')),
                ('region_y', models.FloatField(blank=True, null=True, verbose_name='Position Y')),
                ('region_width', models.FloatField(blank=True, null=True, verbose_name='Largeur de la zone')),
                ('region_height', models.FloatField(blank=True, null=True, verbose_name='Hauteur de la zone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'identification")),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_photos', to='annuaire.person', verbose_name='Personne')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='photos.photo', verbose_name='Photo')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annuaire.person', verbose_name='Identifié par')),
            ],
            options={
                'verbose_name': 'Personne identifiée sur une photo',
                'verbose_name_plural': 'Personnes identifiées sur une photo',
                'constraints': [models.UniqueConstraint(fields=('photo', 'person'), name='unique_photo_person_tag')],
            },
        ),
    ]
