# Generated by Django 6.0.5 on 2026-09-07 16:40

import django.contrib.postgres.search
from django.db import migrations, models

from annuaire.search.migration_ops import create_gin_index_operation


def backfill_album_and_photo_search_indexes(apps, schema_editor):
    from annuaire.search.indexing import apply_index, build_index_payload
    from annuaire.search.registry import get_spec
    from photos.models import Album, Photo

    # .only() pins each queryset to exactly the columns that model's spec
    # weights read AND that already exist at this point in migration history --
    # a later migration on either live model must never cause this historical
    # replay to SELECT a column that doesn't exist yet during a fresh `migrate`.
    album_spec = get_spec(Album)
    for album in Album.objects.only("pk", "title", "description").iterator():
        apply_index(Album, album.pk, build_index_payload(album, album_spec))

    photo_spec = get_spec(Photo)
    # Deliberately no select_related("album") here: that would pull every
    # current Album column along with it, reintroducing the exact hazard
    # .only() exists to avoid. album.description is fetched lazily instead --
    # one extra query per photo, acceptable at this project's scale.
    for photo in Photo.objects.only("pk", "caption", "album").iterator():
        apply_index(Photo, photo.pk, build_index_payload(photo, photo_spec))


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_persontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche'),
        ),
        migrations.AddField(
            model_name='album',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche'),
        ),
        migrations.AddField(
            model_name='photo',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche'),
        ),
        migrations.AddField(
            model_name='photo',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche'),
        ),
        create_gin_index_operation("photos_album_search_vector_gin", "photos_album"),
        create_gin_index_operation("photos_photo_search_vector_gin", "photos_photo"),
        migrations.RunPython(backfill_album_and_photo_search_indexes, migrations.RunPython.noop),
    ]
