# Generated by Django 6.0.5 on 2026-09-07 16:40

import django.contrib.postgres.search
from django.db import migrations, models

from annuaire.search.migration_ops import create_gin_index_operation


def backfill_album_and_photo_search_indexes(apps, schema_editor):
    from annuaire.search.indexing import apply_index, build_index_payload
    from annuaire.search.registry import get_spec
    from photos.models import Album, Photo

    for model in (Album, Photo):
        spec = get_spec(model)
        for instance in model.objects.iterator():
            apply_index(model, instance.pk, build_index_payload(instance, spec))


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_persontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche'),
        ),
        migrations.AddField(
            model_name='album',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche'),
        ),
        migrations.AddField(
            model_name='photo',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche'),
        ),
        migrations.AddField(
            model_name='photo',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche'),
        ),
        create_gin_index_operation("photos_album_search_vector_gin", "photos_album"),
        create_gin_index_operation("photos_photo_search_vector_gin", "photos_photo"),
        migrations.RunPython(backfill_album_and_photo_search_indexes, migrations.RunPython.noop),
    ]
