# Generated by Django 6.0.5 on 2026-08-31 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annuaire', '0011_notifications_opt_in_by_default'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='documents.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.category', verbose_name='Catégorie')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Accès groupe à catégorie',
                'verbose_name_plural': 'Accès groupes à catégories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='document_categories', through='documents.CategoryGroupAccess', to='auth.group', verbose_name='Groupes autorisés'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.category', verbose_name='Catégorie')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='annuaire.person', verbose_name='Déposé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/files/', verbose_name='Fichier')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Texte extrait')),
                ('extraction_status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Terminé'), ('unsupported', 'Non pris en charge'), ('error', 'Erreur')], db_index=True, default='pending', max_length=20, verbose_name="Statut d'extraction")),
                ('extraction_error', models.CharField(blank=True, default='', max_length=255, verbose_name="Erreur d'extraction")),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'extraction")),
                ('ocr_used', models.BooleanField(default=False, verbose_name='OCR utilisé')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/', verbose_name='Vignette')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='categorygroupaccess',
            constraint=models.UniqueConstraint(fields=('category', 'group'), name='unique_category_group_access'),
        ),
    ]
