# Generated by Django 6.0.5 on 2026-08-31 05:19

import documents.storage
import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(storage=documents.storage.get_document_storage, upload_to='files/', validators=[documents.validators.validate_document_extension, documents.validators.validate_document_size], verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=documents.storage.get_document_storage, upload_to='thumbnails/', verbose_name='Vignette'),
        ),
    ]
