# Generated by Django 6.0.5 on 2026-09-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0012_person_death_date_person_deceased'),
        ('documents', '0002_alter_documentfile_file_alter_documentfile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='redactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redacted_documents', to='annuaire.person', verbose_name='Rédigé par'),
        ),
    ]
