# Generated by Django 6.0.5 on 2026-09-07 16:40

import django.contrib.postgres.search
from django.db import migrations, models

from annuaire.search.migration_ops import create_gin_index_operation


def backfill_document_search_index(apps, schema_editor):
    from annuaire.search.indexing import apply_index, build_index_payload
    from annuaire.search.registry import get_spec
    from documents.models import Document

    spec = get_spec(Document)
    # .only() pins this to exactly the columns the Document spec's weights read
    # directly (title/description -- child DocumentFile.extracted_text comes
    # from a separate query, unaffected) AND that already exist at this point
    # in migration history -- a later migration on this same live model must
    # never cause this historical replay to SELECT a column that doesn't exist
    # yet during a fresh `migrate`.
    for document in Document.objects.only("pk", "title", "description").iterator():
        apply_index(Document, document.pk, build_index_payload(document, spec))


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_redactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche'),
        ),
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche'),
        ),
        create_gin_index_operation("documents_document_search_vector_gin", "documents_document"),
        migrations.RunPython(backfill_document_search_index, migrations.RunPython.noop),
    ]
