# Generated by Django 6.0.5 on 2026-09-08 05:34

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models

from annuaire.search.migration_ops import create_gin_index_operation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annuaire', '0017_person_birth_place_person_death_place_and_more'),
        ('photos', '0003_album_search_text_album_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(blank=True, default='', verbose_name='Récit')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche')),
                ('search_text', models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annuaire.person', verbose_name='Créé par')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='annuaire.person', verbose_name='Personne')),
            ],
            options={
                'verbose_name': 'Récit',
                'verbose_name_plural': 'Récits',
            },
        ),
        migrations.CreateModel(
            name='StoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='photos.photo', verbose_name='Photo')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_photos', to='genealogy.story', verbose_name='Récit')),
            ],
            options={
                'verbose_name': "Photo d'un récit",
                'verbose_name_plural': "Photos d'un récit",
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='stories', through='genealogy.StoryPhoto', to='photos.photo', verbose_name='Photos'),
        ),
        migrations.AddConstraint(
            model_name='storyphoto',
            constraint=models.UniqueConstraint(fields=('story', 'photo'), name='unique_story_photo'),
        ),
        create_gin_index_operation("genealogy_story_search_vector_gin", "genealogy_story"),
    ]
