# Generated by Django 6.0.5 on 2026-09-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0017_person_birth_place_person_death_place_and_more'),
        ('documents', '0004_document_search_text_document_search_vector'),
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('kind', models.CharField(blank=True, choices=[('acte_civil', "Acte d'état civil"), ('presse', 'Article de presse'), ('temoignage', 'Témoignage oral'), ('registre', 'Registre ou archive'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Type')),
                ('reference', models.CharField(blank=True, default='', max_length=255, verbose_name='Référence')),
                ('repository', models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu de conservation')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('url', models.URLField(blank=True, default='', verbose_name='Lien')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annuaire.person', verbose_name='Créé par')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genealogy_sources', to='documents.document', verbose_name='Document associé')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.CharField(blank=True, choices=[('birth_date', 'Date de naissance'), ('birth_place', 'Lieu de naissance'), ('death_date', 'Date de décès'), ('death_place', 'Lieu de décès'), ('start_date', 'Date de mariage'), ('end_date', 'Date de fin (relation)'), ('marriage_place', 'Lieu du mariage')], default='', max_length=40, verbose_name='Donnée citée')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='annuaire.person', verbose_name='Personne')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='annuaire.relation', verbose_name='Relation')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='genealogy.story', verbose_name='Récit')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='genealogy.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'constraints': [models.UniqueConstraint(fields=('source', 'story', 'person', 'relation', 'claim'), name='unique_citation_target')],
            },
        ),
    ]
