# Generated by Django 6.0.5 on 2026-09-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0018_person_export_privacy'),
        ('genealogy', '0002_source_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GedcomImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier')),
                ('status', models.CharField(choices=[('pending_review', 'En attente de révision'), ('applied', 'Appliqué'), ('discarded', 'Abandonné')], default='pending_review', max_length=20, verbose_name='Statut')),
                ('raw_content', models.TextField(verbose_name='Contenu brut')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annuaire.person', verbose_name='Déposé par')),
            ],
            options={
                'verbose_name': 'Import GEDCOM',
                'verbose_name_plural': 'Imports GEDCOM',
            },
        ),
        migrations.CreateModel(
            name='StagedFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_xref', models.CharField(blank=True, default='', max_length=20, verbose_name='Référence GEDCOM')),
                ('husband_xref', models.CharField(blank=True, default='', max_length=20, verbose_name="Référence de l'époux")),
                ('wife_xref', models.CharField(blank=True, default='', max_length=20, verbose_name="Référence de l'épouse")),
                ('children_xrefs', models.JSONField(blank=True, default=list, verbose_name='Références des enfants')),
                ('marriage_date', models.DateField(blank=True, null=True, verbose_name='Date de mariage')),
                ('marriage_place', models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu du mariage')),
                ('divorce_date', models.DateField(blank=True, null=True, verbose_name='Date de divorce')),
                ('gedcom_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_families', to='genealogy.gedcomimport', verbose_name='Import')),
            ],
            options={
                'verbose_name': 'Famille importée',
                'verbose_name_plural': 'Familles importées',
            },
        ),
        migrations.CreateModel(
            name='StagedIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_xref', models.CharField(blank=True, default='', max_length=20, verbose_name='Référence GEDCOM')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('birth_place', models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu de naissance')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('death_place', models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu de décès')),
                ('decision', models.CharField(choices=[('create', 'Créer un nouveau profil'), ('merge', 'Fusionner avec un profil existant'), ('skip', 'Ignorer')], default='create', max_length=10, verbose_name='Décision')),
                ('created_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annuaire.person', verbose_name='Profil résultant')),
                ('gedcom_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_individuals', to='genealogy.gedcomimport', verbose_name='Import')),
                ('match_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annuaire.person', verbose_name='Profil correspondant')),
            ],
            options={
                'verbose_name': 'Individu importé',
                'verbose_name_plural': 'Individus importés',
            },
        ),
    ]
