from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    AccountPasswordResetConfirmView,
    AccountPasswordResetDoneView,
    AccountPasswordResetView,
    AddPresenceView,
    AddRelationView,
    BulkAccountCreateView,
    ChaletCreateView,
    ChaletDetailView,
    ChaletListView,
    ChaletOwnersUpdateView,
    ChaletUpdateView,
    CustomLoginView,
    DeletePresenceView,
    DeleteRelationView,
    DirectoryListView,
    FamilyTreeView,
    ForcedPasswordChangeView,
    MagicLinkConfirmView,
    MagicLinkHelpView,
    MagicLinkRequestView,
    MagicLinkSentView,
    MapListView,
    PersonCreateView,
    PersonOwnersUpdateView,
    PersonRelationsView,
    ProfileClaimView,
    ProfileCreateView,
    ProfileDetailView,
    ProfileUpdateView,
    SignupView,
    UpdatePresenceView,
    UpdateRelationView,
    address_search_ajax,
    check_emails_ajax,
    edit_my_profile,
    home,
    my_profile,
    person_search_ajax,
)

urlpatterns = [
    path("", home, name="home"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("profile/", my_profile, name="my-profile"),
    path("profile/create/", ProfileCreateView.as_view(), name="profile-create"),
    path("profile/claim/", ProfileClaimView.as_view(), name="profile-claim"),
    path("profile/edit", edit_my_profile, name="edit-my-profile"),
    path("accounts/bulk-create/", BulkAccountCreateView.as_view(), name="bulk-account-create"),
    path("accounts/check-emails/", check_emails_ajax, name="check-emails-ajax"),
    path("persons/search/", person_search_ajax, name="person-search-ajax"),
    path("addresses/search/", address_search_ajax, name="address-search-ajax"),
    path("password/change/", ForcedPasswordChangeView.as_view(), name="password-change-forced"),
    path("password/reset/", AccountPasswordResetView.as_view(), name="password-reset"),
    path("password/reset/done/", AccountPasswordResetDoneView.as_view(), name="password-reset-done"),
    path(
        "password/reset/<uidb64>/<token>/",
        AccountPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("login/magic/", MagicLinkRequestView.as_view(), name="magic-link-request"),
    path("login/magic/done/", MagicLinkSentView.as_view(), name="magic-link-sent"),
    path(
        "login/magic/<uidb64>/<token>/",
        MagicLinkConfirmView.as_view(),
        name="magic-link-confirm-token",
    ),
    path("login/magic/<uidb64>/", MagicLinkConfirmView.as_view(), name="magic-link-confirm"),
    path("aide/connexion-par-lien/", MagicLinkHelpView.as_view(), name="magic-link-help"),
    path("annuaire/", DirectoryListView.as_view(), name="directory"),
    path("carte/", MapListView.as_view(), name="carte"),
    path("genealogie/", FamilyTreeView.as_view(), name="genealogie"),
    path("genealogie/<int:pk>/", FamilyTreeView.as_view(), name="genealogie-person"),
    path("personne/creer/", PersonCreateView.as_view(), name="person-create"),
    path("personne/<int:pk>/", ProfileDetailView.as_view(), name="personne-detail"),
    path("personne/<int:pk>/update", ProfileUpdateView.as_view(), name="person-edit"),
    path("personne/<int:pk>/owners/", PersonOwnersUpdateView.as_view(), name="person-owners-edit"),
    path("personne/<int:pk>/relations/", PersonRelationsView.as_view(), name="person-relations-edit"),
    path("personne/<int:pk>/relations/add/", AddRelationView.as_view(), name="person-relation-add"),
    path("personne/<int:pk>/relations/<int:rid>/update/", UpdateRelationView.as_view(), name="person-relation-update"),
    path("personne/<int:pk>/relations/<int:rid>/delete/", DeleteRelationView.as_view(), name="person-relation-delete"),
    path("chalets/", ChaletListView.as_view(), name="chalet-list"),
    path("chalets/create/", ChaletCreateView.as_view(), name="chalet-create"),
    path("chalets/<int:pk>/", ChaletDetailView.as_view(), name="chalet-detail"),
    path("chalets/<int:pk>/edit/", ChaletUpdateView.as_view(), name="chalet-edit"),
    path("chalets/<int:pk>/owners/", ChaletOwnersUpdateView.as_view(), name="chalet-owners-edit"),
    path("chalets/<int:pk>/presence/ajouter/", AddPresenceView.as_view(), name="presence-add"),
    path("chalets/<int:pk>/presence/<int:presence_pk>/modifier/", UpdatePresenceView.as_view(), name="presence-edit"),
    path(
        "chalets/<int:pk>/presence/<int:presence_pk>/supprimer/", DeletePresenceView.as_view(), name="presence-delete"
    ),
]
