# Generated by Django 6.0.5 on 2026-05-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annuaire', '0002_alter_account_email_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('post_type', models.CharField(choices=[('BC', 'Busson connection'), ('NORMAL', 'Publication normale')], default='NORMAL', max_length=10, verbose_name='Type de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('authors', models.ManyToManyField(related_name='blog_posts', to='annuaire.person', verbose_name='Auteur(s)')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='publications/', verbose_name='Fichier')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Légende')),
                ('is_image', models.BooleanField(default=False, verbose_name='Est une image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='publications.blogpost', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='annuaire.person', verbose_name='Auteur')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.blogpost', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
    ]
