# Generated by Django 6.0.5 on 2026-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_redactor"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="documents",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="documents.document", verbose_name="Documents liés"
            ),
        ),
    ]
