# Generated by Django 6.0.5 on 2026-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_persontag'),
        ('publications', '0002_blogpost_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='publications', to='photos.album', verbose_name='Albums liés'),
        ),
    ]
