# Generated by Django 6.0.5 on 2026-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_blogpost_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Étiquette')),
                ('accent', models.CharField(blank=True, choices=[('', 'Aucun'), ('gold', 'Doré'), ('accent', 'Alpenglow')], max_length=10, verbose_name='Accent')),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='publications.tag', verbose_name='Étiquettes'),
        ),
    ]
