# Generated by Django 6.0.5 on 2026-09-07 16:40

import django.contrib.postgres.search
from django.db import migrations, models

from annuaire.search.migration_ops import create_gin_index_operation


def backfill_blogpost_search_index(apps, schema_editor):
    from annuaire.search.indexing import apply_index, build_index_payload
    from annuaire.search.registry import get_spec
    from publications.models import BlogPost

    spec = get_spec(BlogPost)
    for post in BlogPost.objects.iterator():
        apply_index(BlogPost, post.pk, build_index_payload(post, spec))


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_tag_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Texte de recherche'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Vecteur de recherche'),
        ),
        create_gin_index_operation("publications_blogpost_search_vector_gin", "publications_blogpost"),
        migrations.RunPython(backfill_blogpost_search_index, migrations.RunPython.noop),
    ]
