# Generated by Django 6.0.5 on 2026-09-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_migrate_post_type_to_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_type',
        ),
    ]
