"""
Django settings for famille_busson project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import tomllib
from pathlib import Path

import environ
from sentry_sdk.types import Event, Hint

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _read_app_version() -> str:
    """Read pyproject.toml's version for the footer -- never importlib.metadata:
    this is a uv *virtual* project (no [build-system] table, --no-install-project
    in the Dockerfile), so no dist-info exists to look up. Empty string on any
    failure (missing/malformed file) -- a wrong footer is fine, a 500 is not."""
    try:
        with open(BASE_DIR / "pyproject.toml", "rb") as f:
            return tomllib.load(f)["project"]["version"]
    except (OSError, tomllib.TOMLDecodeError, KeyError):
        return ""


APP_VERSION = _read_app_version()

env = environ.Env(
    DEBUG=(bool, True),
)
# Local dev convenience only: a .env file at the repo root is optional and gitignored.
# In production, env vars are injected by docker-compose's env_file, no .env is read here.
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is for local development only; production always sets SECRET_KEY.
SECRET_KEY = env("SECRET_KEY", default="django-insecure-s+nx2_m67p&#h8j$7or2w)*dnhu@+!fy=@kwvn3i)engc)z1g=")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    USE_X_FORWARDED_HOST = True
    # Otherwise the compose healthcheck's plain-HTTP request gets a 301 and never
    # actually executes the view -- silently reporting healthy either way (curl -f
    # treats a 3xx as success) or falsely failing. Matched against the path with no
    # leading slash, per SECURE_REDIRECT_EXEMPT's own semantics.
    SECURE_REDIRECT_EXEMPT = [r"^healthz$"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_q",
    "django.contrib.postgres",
    "annuaire",
    "publications",
    "documents",
    "photos",
    "events",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Early, so every log line from anywhere further down the chain (including
    # error responses) carries the same request_id.
    "annuaire.middleware.RequestIdMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "annuaire.middleware.ForcePasswordChangeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "famille_busson.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "annuaire.context_processors.site_version",
            ],
            "libraries": {
                "crispy_forms_filters": "crispy_forms.templatetags.crispy_forms_filters",
            },
        },
    },
]

CRISPY_TEMPLATE_PACK = "bootstrap5"

WSGI_APPLICATION = "famille_busson.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {"default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")}


# Cache -- shared across gunicorn workers via Valkey/Redis in production (db 0; db 1 is
# reserved for the background task queue's broker, see docs/deployment.md). Defaults to
# LocMemCache so dev/tests never need a real cache server.
CACHES = {"default": env.cache("CACHE_URL", default="locmemcache://")}


# Background task queue (django-q2) -- reuses db 1 of the same Valkey instance CACHES
# uses db 0 of. See docs/background_tasks.md.
Q_CLUSTER = {
    "name": "famille_busson",
    "workers": 2,
    "recycle": 20,  # bounds per-worker memory growth from OCR/PyMuPDF over many runs
    "timeout": 300,
    "retry": 600,  # MUST stay > timeout, or django-q2 re-queues a still-running task
    "max_attempts": 3,
    "save_limit": 250,  # bounds the django_q success-log table in Postgres
    "catch_up": True,
    "redis": env("QUEUE_URL", default="redis://cache:6379/1"),
    "sync": env.bool("Q_SYNC", default=DEBUG),
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication
AUTH_USER_MODEL = "annuaire.Account"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
LOGIN_URL = "/annuaire/login/"
# Django's default (3 days) is too tight for an invite/reset email that may sit
# unread over a weekend.
PASSWORD_RESET_TIMEOUT = env.int("PASSWORD_RESET_TIMEOUT", default=60 * 60 * 24 * 7)
# Passwordless "magic link" login -- much shorter-lived than a password reset,
# since it grants an immediate session rather than just a chance to set a
# password.
MAGIC_LINK_TIMEOUT = env.int("MAGIC_LINK_TIMEOUT", default=15 * 60)

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # ManifestStaticFilesStorage requires collectstatic to have run (it resolves
        # every {% static %} tag through staticfiles.json) -- fine in prod where the
        # entrypoint always runs collectstatic first, but breaks dev/tests, which never
        # do. Plain StaticFilesStorage resolves straight from each app's static/ dir.
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        if DEBUG
        else "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# In dev, serve static files straight from each app's static/ dir (no collectstatic
# needed). In prod, serve the collected+hashed STATIC_ROOT built at container startup.
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Protected document storage -- deliberately outside MEDIA_ROOT/media_serve's reach
# (see documents/storage.py). No MEDIA_URL-style public URL: files are only ever
# served through documents' own access-checked endpoint.
DOCUMENTS_ROOT = os.path.join(BASE_DIR, "documents_data")

# Protected photo storage -- same posture as DOCUMENTS_ROOT above (see
# photos/storage.py). Deliberately nested *inside* documents_data rather than a
# sibling volume: documents_data is the one volume scripts/backup.sh,
# scripts/restore.sh, docker-compose.prod.yml and annuaire/health.py already
# know about, so nesting here means the family photo archive is backed up for
# free instead of silently missing from a forgotten new volume.
PHOTOS_ROOT = os.path.join(DOCUMENTS_ROOT, "photos")

# Django's default LOGGING only sends the 'console' handler output when DEBUG=True
# (RequireDebugTrue filter) -- in prod (DEBUG=False) that made every 500 invisible in
# `docker logs`, since ADMINS/mail_admins isn't configured either. Force errors to
# console unconditionally so gunicorn's stdout (captured by Docker) always has them.
#
# LOG_FORMAT selects plain console output (readable in a dev terminal) or
# one-JSON-object-per-line (grep/log-aggregator friendly), independent of DEBUG so
# either can be forced for local debugging. A root ("") logger is what makes
# __name__-based loggers elsewhere (e.g. annuaire/file_cleanup.py) actually reach a
# handler -- previously only "django"/"django.request" were configured, so anything
# else fell through to logging's unformatted lastResort handler.
LOG_FORMAT = env("LOG_FORMAT", default="console" if DEBUG else "json")
_ACTIVE_LOG_HANDLER = "json" if LOG_FORMAT == "json" else "console"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {"()": "annuaire.middleware.RequestIdLogFilter"},
    },
    "formatters": {
        "console": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
        "json": {"()": "annuaire.log_formatters.JsonFormatter"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_id"],
            "formatter": "console",
        },
        "json": {
            "class": "logging.StreamHandler",
            "filters": ["request_id"],
            "formatter": "json",
        },
    },
    "root": {
        "handlers": [_ACTIVE_LOG_HANDLER],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": [_ACTIVE_LOG_HANDLER],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": [_ACTIVE_LOG_HANDLER],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Error monitoring (Sentry) -- inert (no-op) unless SENTRY_DSN is set, so dev/CI/tests
# are entirely unaffected. send_default_pii is always False: this site holds personal
# data on identifiable EU residents. Errors only, never performance/profiling data.


def _sentry_before_send(event: Event, hint: Hint) -> Event:
    """Defense in depth against exactly the kind of personal data this site holds:
    drop cookies wholesale, and any extra/context value filed under a key literally
    named "email" (case-insensitive), regardless of where it came from.

    A module-level function (not a closure) so it's importable and unit-testable
    without needing a real `sentry_sdk.init()` call -- same reasoning as
    `_default_site_base_url` above.
    """
    request = event.get("request")
    if request:
        request.pop("cookies", None)
    for section in ("extra", "contexts"):
        data = event.get(section)
        if isinstance(data, dict):
            for key in list(data):
                if key.lower() == "email":
                    data.pop(key)
    return event


SENTRY_DSN = env("SENTRY_DSN", default="")
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        release=APP_VERSION,
        environment=env("SENTRY_ENVIRONMENT", default="development" if DEBUG else "production"),
        send_default_pii=False,
        before_send=_sentry_before_send,
        traces_sample_rate=0.0,
        profiles_sample_rate=0.0,
    )

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGOUT_REDIRECT_URL = "/annuaire/login/"

# Email
# Generic SMTP settings, left empty by default (console backend). Production fills in
# EMAIL_HOST/EMAIL_HOST_USER/EMAIL_HOST_PASSWORD etc. in /srv/bubu/.env once a provider
# is chosen.
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@bubu.reboulip.fr")


def _default_site_base_url(csrf_trusted_origins: list[str], allowed_hosts: list[str]) -> str:
    """Best-effort non-localhost fallback for SITE_BASE_URL when it's left unset.

    Emails are built outside a request, so the domain can't come from
    request.build_absolute_uri() -- silently defaulting to localhost there is worse
    than deriving a real host from settings already known to be correct in production.
    """
    if csrf_trusted_origins:
        return csrf_trusted_origins[0]
    for host in allowed_hosts:
        if host in ("*", "localhost", "127.0.0.1") or host.startswith("."):
            continue
        return f"https://{host}"
    return "http://localhost:8000"


# Base URL used to build absolute links in emails sent outside a request context
# (birthday reminders, blog post notifications) -- request.build_absolute_uri() isn't
# available there. Production sets this explicitly; the derived fallback above only
# guards against it being forgotten (see annuaire.checks for the accompanying warning).
SITE_BASE_URL = env("SITE_BASE_URL", default=_default_site_base_url(CSRF_TRUSTED_ORIGINS, ALLOWED_HOSTS))
